### ISSUE TITLE
Add information on being added as an editor for GitBook

### ISSUE THREAD

**Issue by taowa** [neuropoly/intranet.neuro.polymtl.ca#5]
As far as I can tell, we're not documenting how someone comes to end up with access to GitBook. As fun as editing markdown by hand may be, this should probably be documented here.

**Comment by kousu** [comment]
It's documented on https://neuropoly.gitbook.io/neuropoly-lab/. The instructions are

1. Get a google account
2. Get granted access to the shared credentials file on google docs
3. Click the Gitbook Invite link in there

Another method, not documented there, is

1. Get a slack account
2. Go to #website
3. Click the Invite link which is Bookmarked to that channel

**Comment by kousu** [comment]
Superseded by #21 (thankfully). Now this is part of standard onboarding, and I updated it over in https://github.com/neuropoly/onboarding/commit/ee422aad0d34027e537da5ee93b3948870b63371#diff-5dbc3be7899771842055d4f0c692e88f1a5a9fb3a80734a6c02417a67e632a48.

My plan is to sync membership-card.md out of the private repo and into this repo regularly -- maybe with an Action to help out, so that will take care of this fully.
